### ISSUE TITLE
Microsoft Account List

### ISSUE THREAD

**Issue by kpman** [web-seminar/slide-v3#10]
* 請留言回覆，格式參考如下
> 姓名 - 系級 - account

**Comment by kpman** [comment]
Daniel - 資管 - daniel.tseng@yoctol.com

**Comment by b03901152** [comment]
陳景由-電機三-b03901152@ntu.edu.tw

**Comment by theRolev** [comment]
黃柏瑞 - 電機三 - viraysrolev@hotmail.com

**Comment by YuanTingHsieh** [comment]
謝沅廷 - 電機五 - d611301@yahoo.com.tw

**Comment by PatrickChen83** [comment]
陳奕安 - 電機碩ㄧ - a73603@hotmail.com

**Comment by NekOrz** [comment]
陳俞兆 - 電機四 - joe1256joe@hotmail.com.tw

**Comment by zeroHuang0516** [comment]
黃于瑄 - 電機三 - b03901156@ntu.edu.tw

**Comment by liu115** [comment]
劉岳承 - 資工三 - liujimmy8877@hotmail.com

**Comment by Oliveck10** [comment]
彭奕豪 - 資工二 - [oliveck10@gmail.com](url)

**Comment by awinder0230** [comment]
郭子生 - 電機三 - awinder0230@gmail.com

**Comment by dingcsw** [comment]
陳尚緯 - 電機三 - dingcsw@outlook.com

**Comment by danny8508021** [comment]
王彥稀 - 電機三 - danny8508021@gmail.com

**Comment by dingcsw** [comment]
陳尚緯 - 電機三 - dingcsw@outlook.com

**Comment by BenTsai85** [comment]
蔡丞昊 - 電機三 - benjamin850418@gmail.com

**Comment by tzupengwang** [comment]
王子朋 - 電機三 - tzupengwang@gmail.com

**Comment by Chung-I** [comment]
李仲翊 - 電機三 - leon129506@gmail.com

**Comment by jasonwu0731** [comment]
吳建昇 - 電機五 - b01901045@ntu.edu.tw

**Comment by chenhsiwen** [comment]
陳璽文 - 電機三 - [chentp6vu3jp6@gmail.com](url)

**Comment by tom0731** [comment]
樊恩宇 - 電子碩一 - (rock15688@gmail.com)

**Comment by B03901108** [comment]
黃暐倫 - 電機三 - 271828182euler@gmail.com

**Comment by net5566** [comment]
曾昶凱 - 電機四 - crynet5566@outlook.com

**Comment by b02901071** [comment]
黃淞楓 - 電機四 - sungsung3201@gmail.com

**Comment by Ichika719** [comment]
黃琬婷 - 圖資碩一 - sarada719@hotmail.com

**Comment by chentsulin** [comment]
Done
